### ISSUE TITLE
setting SI (SI6048US ?) params over can, or rs485

### ISSUE THREAD

**Issue by dalklein** [sshoecraft/solardirector#1]
Hello,  I heard you might be figuring out how to set SI parameters over RS485?  

I have a DC solar components installed in garage, the SunnyIslands and the pair of FLA forklift batteries, with some other solar & batteries.  I'd really like to change SI params over can or rs485 from the RPi that I am so far using to monitor them over CAN.  Similar to madsci, and your setup?,  but the CAN data messages are different if FLA or Lithium is selected.  So still some to figure out there, haven't come across any doc for the FLA message, and some are obvious, others are not.

 It looks like you're going to have multiple JBD bluetooth bmses;  that's a neat low cost way to monitor a number of separate lithium strings.  I have one of those BMS half set up in a 36v Leaf pack in ElecTrak tractor, which I charge and discharge to run the house when not used to mow the yard.  Goal is to do that with an ESP32 over UART to the JBD bms.

Thanks,   Dale

**Comment by sshoecraft** [comment]
Dale, I got the rs485 card for my sunny island from here:

https://www.thepowerstore.com/sma-rs485-card-for-legacy-sunny-boy-inverters.html

Then I got the yasi library from SMA:

https://www.sma.de/en/products/monitoring-control/yasdi.html

And a CAN/485 hat for my RPI3B+:

https://www.amazon.com/gp/product/B07DNPFMRW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1


Then I wrote a util for getting/setting params.  I just uploaded a project with the a statically compiled binary for the Pi here:

https://github.com/sshoecraft/siutil


You'll want to set the YASDI_SRC= param in the Makefile if you want to build it yourself.   Personally, I just put the siutil directory right in the yasi source tree but it shouldnt depend on that.   Also, I HAVE made modifications to the yasdi source tree to make it build without using dynamically loaded device drivers (for serial/ip) - they are statically compiled into the library.  I don't know if I can distribute my changes to the lib - I'll need to review the licensing agreement for it from SMA.

To use the util, set the yasdi.ini the device you'll be using and the baud rate.  I set the baud rate on the SI to 19200 to make it go a bit faster (my Pi is in the same room as the SI).   You might want to do this before running the binary for the 1st time as it downloads the device info into devices/<device>.bin and on 1200 baud it takes forever.  It doesn't say what it's doing and seems like it's hung or not working.   I provided one in the project for my 6048 - if yours is the same it might use it.   Keep in mind it puts the devices dir in the same place as yasdi.ini

To get a list of spot value channels:  ./siutil -l
To get a list of configuration parameters: ./siutil -l -p
To list all channels: ./siutil -l -a

To get a value for a channel:

./siutil GnCoolTm
5.000000

To set a value:

./siutil GnCoolTm 6

Get the value again:

./siutil GnCoolTm
6.000000

If a channel takes text string options and you want to list the options:

./siutil -l GdManStr
---
Auto
Stop
Start

You can then use the option name to set the channel (vs using a number)

./siutil GdManStr Stop

Get the new value:

./siutil GdManStr
Stop

sitool definitely shows the grid no longer connected:

sitool | grep ^Grid
Grid On                   false

https://github.com/sshoecraft/sitool

Start the grid in the same way

./siutil GsManStr Start

Need to wait for your timeout, but sitool should show the grid connected after (I set mine to 120 seconds - default is 300)

./siutil GdVldTm
120.000000

**Comment by sshoecraft** [comment]
i'll update the readme with this stuff but the project is still in pre-alpha stage.  I really need to revamp the yasdi library.

**Comment by sshoecraft** [comment]
By way, the tractor is super cool!  I've been thinking about doing the same to my old '71 cub cadet - it blew an engine and rather than repair the engine, I'm going to convert it to electric.  It has the tiller attachment on it and I have a small trailer for it.

Also, have you seen my thread on the ESP-01s attached to my JBD BMSs?

https://diysolarforum.com/threads/jbd-bms-wi-fi-module.17252/

I have 14 of these BMS in my 50k powerwall of BMW EV batteries:

![image](https://user-images.githubusercontent.com/46583549/109547708-52077880-7a91-11eb-9178-593ad95b9e56.png)

(display program is my cellmon project:  https://github.com/sshoecraft/cellmon)

**Comment by dalklein** [comment]
Thank You!    I will try the siutil as soon as I get the 485 adapters on each end!
